version: '3.8'

name: motorq-dev

services:
  postgres:
    image: postgres:15
    container_name: motorq_postgres_dev
    environment:
      POSTGRES_DB: motorq_fleet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - motorq-dev-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: motorq_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@motorq.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    networks:
      - motorq-dev-network

volumes:
  postgres_dev_data:
  pgadmin_dev_data:

networks:
  motorq-dev-network:
    driver: bridge
